### ISSUE TITLE
Citrine informatics in the matminer_examples not working

### ISSUE THREAD

**Issue by nitin0301** [hackingmaterials/matminer_examples#50]
Getting following error:

Traceback (most recent call last):
  File "MP_Citrine_MDF_MPDS_Masher.py", line 37, in <module>
    from matminer.data_retrieval.retrieve_Citrine import CitrineDataRetrieval
  File "matminer/data_retrieval/retrieve_Citrine.py", line 2, in <module>
    from citrination_client import CitrinationClient, ChemicalFieldQuery, \
ModuleNotFoundError: No module named 'citrination_client'

**Comment by nitin0301** [comment]
Thanks Logan.

I installed the citrination-client. I get somewhat different error:

Traceback (most recent call last):
  File "test_citrine.py", line 22, in <module>
    from matminer.data_retrieval.retrieve_Citrine import CitrineDataRetrieval
  File "/matminer/data_retrieval/retrieve_Citrine.py", line 2, in <module>
    from citrination_client import CitrinationClient, ChemicalFieldQuery, \
ImportError: **cannot import name 'PifSystemQuery'**

Process finished with exit code 1

**Comment by nitin0301** [comment]
Figured it out. It needed me to install pif-ingestor. Thanks Logan for your help.

Nitin

**Comment by YuanJ-i** [comment]
thx. Time saved.
