### ISSUE TITLE
JSON issues with 'kernel_ridge_SCM_OFM' example

### ISSUE THREAD

**Issue by dptru10** [hackingmaterials/matminer_examples#54]
The 'kernel_ridge_scm_ofm' example script produces the following error when trying to load the 'flla' dataset: 

REMOVE UNSTABLE ENTRIES: False
USE FABER DATASET: True
USE TERNARY OXIDE DATASET: False
NUMBER OF JOBS: 24
DEBUG MODE: False
Traceback (most recent call last):
  File "kernel_ridge_SCM_OFM.py", line 67, in <module>
    df = load_dataset("flla")
  File "/home/dennis/.local/lib/python3.5/site-packages/matminer/datasets/dataset_retrieval.py", line 63, in load_dataset
    df = load_dataframe_from_json(data_path)
  File "/home/dennis/.local/lib/python3.5/site-packages/matminer/utils/io.py", line 58, in load_dataframe_from_json
    dataframe_data = json.load(f, cls=MontyDecoder)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Any help in debugging is appreciated.

**Comment by ardunn** [comment]
Hey @dptru10!

Thanks for the heads up, this issue must have slipped our radar. We have just updated this script in #55. We recommend using the newest version of matminer to run the script. If you still have issues with it,  please open a topic on our help forum https://hackingmaterials.discourse.group
