### ISSUE TITLE
from automatminer import MatPipe -> IndexError: list index out of range

### ISSUE THREAD

**Issue by liuxiaotong15** [hackingmaterials/matminer_examples#58]
sorry, but I just pip install the lib, then import failure...
could anyone give me some idea about it?
thanks

```
Python 3.7.4 (default, Dec 17 2019, 17:07:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from automatminer import MatPipe
/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.unsupervised module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/automatminer/__init__.py", line 2, in <module>
    from automatminer.featurization import AutoFeaturizer  # noqa
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/automatminer/featurization/__init__.py", line 1, in <module>
    from .core import AutoFeaturizer  # noqa
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/automatminer/featurization/core.py", line 27, in <module>
    from automatminer.featurization.sets import (
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/automatminer/featurization/sets.py", line 10, in <module>
    import matminer.featurizers.structure as sf
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/matminer/featurizers/structure.py", line 36, in <module>
    from matminer.featurizers.site import OPSiteFingerprint, \
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/matminer/featurizers/site.py", line 1670, in <module>
    class LocalPropertyDifference(BaseFeaturizer):
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/matminer/featurizers/site.py", line 1695, in LocalPropertyDifference
    def __init__(self, data_source=MagpieData(), weight='area',
  File "/home/inode01/xiaotong/code/mossbauer_preprocess/venv_moss/lib/python3.7/site-packages/matminer/utils/data.py", line 215, in __init__
    prop_value = float(lines[atomic_no - 1])
IndexError: list index out of range
```

**Comment by ardunn** [comment]
Hey there, thanks for the question.


The error actually has to do with the specific version of pymatgen and matminer you're using (this is a well-known problem with matminer <=0.6.2 with newer pymatgen releases). You should install automatminer's requirements file using the requirements file here: https://github.com/hackingmaterials/automatminer/blob/master/requirements.txt

If you still need help, please ask on our help forum: https://matsci.org

**The github issue tracker is for development only.**

**Comment by liuxiaotong15** [comment]
thanks
